### ISSUE TITLE
pe076公式有误

### ISSUE THREAD

**Issue by renph** [sorrowise/euler#3]
博文 https://pe.metaquant.org/pe076.html
状态转移方程中， n<=k 时, p(n,k) = 1+p(n,k-1)。应为 p(n,k) = 1+p(n,n-1)

**Comment by sorrowise** [comment]
> 博文 https://pe.metaquant.org/pe076.html
> 状态转移方程中， n<=k 时, p(n,k) = 1+p(n,k-1)。应为 p(n,k) = 1+p(n,n-1)

是的，代码是对的，公式输错了，感谢反馈。
